# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  node: circleci/node@5.0.2  # for using yarn cache automatically
  slack: circleci/slack@4.1  # for notification to slack
jobs:
  build_with_node:
    docker:
      - image: 'cimg/node:16.15.0'  # can use executor by node orbs or we can set manually
    steps:
      - checkout
      - run: echo "Build started on `date`"
      - node/install-packages:
          override-ci-command: yarn
          check-cache: detect # try using yarn.lock
      - run: yarn run build
      - run: echo "Test started on `date`"
      - run: yarn run test
      - run: mkdir workspace && mv out workspace/out
      - persist_to_workspace:
          root: workspace
          paths: out
  deploy:
    docker:
      - image: 'cimg/node:16.15.0'
    steps:
      - add_ssh_keys:
          fingerprints:
            - "a3:fc:07:7d:9b:38:05:99:b2:8f:ec:fb:56:a1:6b:4a"
      - checkout
      - run: echo "deploy my app"
      - attach_workspace:
          at: workspace
      - run: npm install -g --silent gh-pages@2.0.1
      - run: git config user.email "ivanjaya@fivejack.com"
      - run: git config user.name "Ivan"
      - run: gh-pages --dist workspace/out
workflows:
  version: 2
  build-to-beta-master:   
    jobs:
      - approve_build: # manual approval
          filters:
            branches:
              only:
                - beta
          type: approval 
      - build_with_node : # build started
          requires:
            - approve_build
      - deploy: # deploy started
          requires:
            - build_with_node
